version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install --ignore-engines
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://examteste/
artifacts:
  files:
    - '**/*'
  base-directory: build
